[package]
name = "system"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
sha2 = "0.10"
flate2 = "1.0"
tar = "0.4"
walkdir = "2.3"
pretty = { git = "https://github.com/Dj-Codeman/pretty.git" }